### ISSUE TITLE
SIGSEGV if tun device is present

### ISSUE THREAD

**Issue by zyddnys** [EstebanBorai/local-ip-address#24] opened 2021-09-06 01:16 UTC
The list all interface and IP program crashes with `'cargo run' terminated by signal SIGSEGV (Address boundary error)` if I create a tun device using `sudo ip tuntap add tun0 mode tun`.
code:
```rust
use local_ip_address::list_afinet_netifas;

fn main() {
    let network_interfaces = list_afinet_netifas().unwrap();

    for (name, ip) in network_interfaces.iter() {
        println!("{}:\t{:?}", name, ip);
    }
}
```

**Comment by EstebanBorai** [comment] 2021-09-06 02:39
Hello @zyddnys! Thanks for reporting this issue!
I'm checking on your error and I was able to reproduce it.

The invalid access occurs here:
https://github.com/EstebanBorai/local-ip-address/blob/078a53fcea9a946eae9ee5a60bac5f43adc0e1f9/src/linux.rs#L149

The pointer `ifa_addr` is `null`, thus access to its fields is not valid, and when we attempt to access the `sa_family` field we receive SIGSEGV.

If you check for your network interfaces running:

```bash
ip link show
```

You will get this output:

```bash
# Network interfaces from your system..
8: tun0: <POINTOPOINT,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 500
    link/none
```

Note that we don't have an address assigned to our `tun0` interface, instead we have `link/none` in it's place.

```bash
sudo ip tuntap add tun0 mode tun
```

### Solution Draft

I think I've to introduce support for network interfaces with no address.
So instead of having:

```rust
Vec<(String, IpAddr)>
```

For the list of network interfaces, we could have:

```rust
Vec<(String, Option<IpAddr>)>
```

Or perhaps, even more descriptive:

```rust
enum NetworkInterfaceAddress {
    AfInet,
    AfInet6,
}

struct NetworkInterface {
    name: String,
    ip_address: Option<IpAddr>,
    family: NetworkInterfaceFamily,
}
```

What do you think?

**Comment by zyddnys** [comment] 2021-09-06 21:45
Sounds great, thank you for the help

**Comment by EstebanBorai** [comment] 2021-09-06 22:01
Thanks to you! I will be working on this and get back to you when its ready!

**Comment by EstebanBorai** [comment] 2021-09-13 05:24
Hi @zyddnys, I hope you are doing well!
I've been discussing improvements to the API in #26, I would appreciate your suggestions there as we were talking about something similar here.

Take a look to this struct definition here:
https://github.com/EstebanBorai/local-ip-address/issues/26#issuecomment-915752769

Let me know your comments!

**Comment by EstebanBorai** [comment] 2023-08-19 13:05
This error is not happening anymore due to the patch on #78. Now we actually need support for TUN devices.

**Closed** 2023-08-19 13:05 UTC
Labels: bug, os-linux
